Remove hhvm test
because
```
Fatal error: Uncaught Error: Parameter $constraints is variadic and has a type constraint (Constraint); variadic params with type constraints are not supported in non-Hack files in phar://phpunit-6.5.2.phar/phpunit/Framework/Constraint/LogicalAnd.php:29
```